name: first github actions
on: pull_request

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install dependencies & format code for express-gateway
        run: |
          cd express-gateway
          bun install
          bunx @biomejs/biome check --write ./src
      - name: install dependencies & format code for blog-service
        run: |
          cd blog-service
          bun install
          bunx @biomejs/biome check --write ./src  
          
